### ISSUE TITLE
'No window object present' in browser-less node

### ISSUE THREAD

**Issue by tinnvec** [HearthSim/npm-hearthstonejson#2]
When using the package in a server role, node doesn't have a 'window' object, which is used for the XMLHttpRequests the package makes.

One can use https://github.com/rstacruz/jsdom-global as a way of providing a window object as a stop-gap, but removing reliance on the window object or adding checks for window vs global would be the most robust route to go, I think.

**Comment by beheh** [comment]
I've changed the build process, so the package should be using the Node's native "https" as of 0.0.12.
